### ISSUE TITLE
AArch64 missing details tasks

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2196]
List to track not yet implemented or faulty details of AArch64

- [x] Warning if `arm64` is passed to cstool
- [x] SME vector lead/store/read/write have incorrect outs/ins set
- [x] `za` writes are not listed in register write list
- [ ] U/SBFM alias modulo change depending on S and N bit. (wait for encoding info).
- [x] Memory operands/index regs labeled incorrectly (https://github.com/capstone-engine/capstone/issues/2285)

**Comment by FinnWilkinson** [comment]
Hi @Rot127, I'm not sure what the timeline is on these issues, but another which I have just spotted in `next` branch since the AArch64 auto-sync PR merge is that `arch/AArch64/AArch64GenRegisterName.inc` needs updating as was done with the rest of the AArch64 `.inc` files. 

Given the use of LLVM 16.x for the generation of these files, SME2 & SVE2 is now included which introduced a new `zt0` register. This is present in the `AArch64GenRegisterInfo.inc` file, but not the file mentioned above.

**Comment by Rot127** [comment]
`AArch64GenRegisterName.inc` Shouldn't be there anymore actually. It is no longer used and I just forgot to delete it.

>  I'm not sure what the timeline is on these issues,

Timeline is a little hot topic. I have to work on other stuff most the time so it will take a little until all the left issues will be done. Going to finish these ones here first though.
