### ISSUE TITLE
Rework DIET mode

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2404]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [ ] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [x] Other (elaborated below)

**Describe the feature you'd like**

The DIET build of Capstone is untested and not done for the auto-sync architectures yet.
But besides that, it is also not well defined, how it behaves (see https://github.com/capstone-engine/capstone/issues/1883) 

We should define, how exactly the DIET mode works and very much consider to build it with a smaller libc like [picolibc](https://github.com/picolibc/picolibc)

**TODO**

- [ ] https://github.com/capstone-engine/capstone/issues/2368
- [ ] Define what DIET builds provide and what not.
- [ ] Wrap more code in DIET guards for auto-sync builds.
- [ ] Reconsider what should be decoded in DIET mode (eg. no mnemonic, but only details etc.). Maybe enable disable it optionally? See: https://github.com/capstone-engine/capstone/issues/2780#issuecomment-3224635940
- [ ] Non-PIC build should be possible. So pointers and all can be in read-only maps.
