### ISSUE TITLE
[Tests] Further improvements

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2453]
**100% Test coverage of details**

(Only new or refactored modules are listed)

| file                                                          | coverage | covered     | Done |
|---------------------------------------------------------------|----------|-------------|------|
| arch/LoongArch/LoongArchMapping.c                             | 67.29%   | 144 / 214   |  No  |
| arch/PowerPC/PPCMapping.c                                     | 72.78%   | 254 / 349   |  No  |
| arch/AArch64/AArch64Mapping.c                                 | 60.47%   | 918 / 1518  |  No  |
| arch/TriCore/TriCoreMapping.c                                 | 45.00%   | 45 / 100    |  No  |
| arch/Alpha/AlphaMapping.c                                     | 86.08%   | 68 / 79     |  No  |
| arch/ARM/ARMMapping.c                                         | 61.68%   | 792 / 1284  |  No  |
| arch/HPPA/HPPAMapping.c                                       | 29.85%   | 20 / 67     |  No  |

- [ ] Add workflow to test it never falls under 100% again for each file.
- [ ] Ensure fuzzing reaches test coverage of 100%

**API integration tests**

- [ ] Make API integration tests actual tests (not just printing to `stdout`)

**Fuzzer**

- [ ] https://github.com/capstone-engine/capstone/issues/2454

**Others**

- [x] https://github.com/capstone-engine/capstone/issues/2438
- [ ] https://github.com/capstone-engine/capstone/issues/2368
