### ISSUE TITLE
Fully generated bindings

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2468]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [ ] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [x] Other (elaborated below)

**Describe the feature you'd like**

There is no reason to not generate most of the bindings. Especially the representation of the detail structs of several architectures should be easy.

This would help a lot, because currently we got bugs due to fields added to the C structs, but not to the Python bindings. Before https://github.com/capstone-engine/capstone/pull/2456 we didn't even detected in the PR.

**TODO and related tasks**

- [ ] https://github.com/capstone-engine/capstone/issues/2851
- [x] https://github.com/capstone-engine/capstone/issues/2852
- [ ] https://github.com/capstone-engine/capstone/issues/2841
- [ ] https://github.com/capstone-engine/capstone/issues/2609

**Additional context**

Same for all other bindings.

**Comment by AndrewQuijano** [comment]
Closing this would close #2609
